"""
SAVE stage: publish outputs atomically, partitioned by month.

Rerun behaviour: the same month always maps to the same partition directory,
which is written to a temp directory first and then swapped in. A rerun
therefore REPLACES the month instead of appending duplicates, and a crash
mid-write never leaves a half-written partition in place.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import duckdb

from .logging_utils import get_logger

log = get_logger("save")


def _q(path: Path) -> str:
    return str(path).replace("\\", "/").replace("'", "''")


def save_month(con: duckdb.DuckDBPyConnection, month: str, processed_dir: Path,
               validation_report: dict, gates: list[dict]) -> Path:
    final_dir = processed_dir / f"month={month}"
    tmp_dir = processed_dir / f".tmp_month={month}"
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True)

    con.sql(f"copy fact_trip to '{_q(tmp_dir / 'fact_trip.parquet')}' (format parquet, compression zstd)")
    con.sql(f"copy (select * from trips_validated where not is_valid) "
            f"to '{_q(tmp_dir / 'quarantine.parquet')}' (format parquet, compression zstd)")
    con.sql(f"copy quarantine_summary to '{_q(tmp_dir / 'quarantine_summary.csv')}' (header, delimiter ',')")
    con.sql(f"copy reconciliation_zones to '{_q(tmp_dir / 'reconciliation_zones.csv')}' (header, delimiter ',')")
    con.sql(f"copy (select * from metrics_monthly where month = '{month}') "
            f"to '{_q(tmp_dir / 'metrics.csv')}' (header, delimiter ',')")
    report = dict(validation_report)
    report["gates"] = gates
    (tmp_dir / "validation_report.json").write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")

    if final_dir.exists():
        shutil.rmtree(final_dir)        
    tmp_dir.replace(final_dir)
    log.info("partition published | month=%s | dir=%s | files=%d", month, final_dir,
             len(list(final_dir.iterdir())))
    return final_dir


def save_combined(processed_dir: Path, docs_dir: Path, months: list[str]) -> Path:
    """Rebuild the cross-month evidence table from the published partitions."""
    con = duckdb.connect()
    parts = [processed_dir / f"month={m}" / "metrics.csv" for m in months]
    parts = [p for p in parts if p.exists()]
    if not parts:
        raise FileNotFoundError("no metrics partitions to combine")
    files = ", ".join(f"'{_q(p)}'" for p in parts)
    con.sql(f"create table m as select * from read_csv([{files}], header=true, union_by_name=true)")
    out = processed_dir / "metrics_monthly.csv"
    tmp = processed_dir / ".metrics_monthly.csv.tmp"
    con.sql(f"copy (select * from m order by month, case when borough='ALL NYC' then 0 else 1 end, borough) "
            f"to '{_q(tmp)}' (header, delimiter ',')")
    tmp.replace(out)

    rows = con.sql("""select month, borough, raw_rows, valid_trips, data_yield_pct, median_duration_min,
                             p90_duration_min, median_speed_mph, airport_trip_share_pct,
                             tlc_published_pickups, recon_gap_pct
                      from m where borough in ('ALL NYC','Manhattan','Queens','Brooklyn','Bronx')
                      order by month, case when borough='ALL NYC' then 0 else 1 end, borough""").fetchall()
    hdr = ["month", "borough", "raw_rows", "valid_trips", "yield_%", "median_dur_min", "p90_dur_min",
           "median_mph", "airport_%", "tlc_published", "gap_%"]
    lines = ["| " + " | ".join(hdr) + " |", "|" + "---|" * len(hdr)]
    for r in rows:
        lines.append("| " + " | ".join("" if v is None else (f"{v:,}" if isinstance(v, int) else str(v)) for v in r) + " |")
    docs_dir.mkdir(parents=True, exist_ok=True)
    md = docs_dir / "evidence_table.md"
    md.write_text("# Evidence table (generated by run_pipeline.py)\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
    log.info("combined metrics written | rows=%d | csv=%s | md=%s", len(rows), out, md)
    return out
